version: 2

sources:
  - name: northwind
    description: "Northwind Traders sample database"
    database: Northwind
    schema: dbo
    tables:
      - name: Customers
        description: "Customer information including company details and contact info"
        columns:
          - name: CustomerID
            description: "Primary key - unique customer identifier"
          - name: CompanyName
            description: "Name of the customer company"
          - name: ContactName
            description: "Name of the primary contact person"
          - name: Country
            description: "Country where the customer is located"

      - name: Orders
        description: "Order header information"
        columns:
          - name: OrderID
            description: "Primary key - unique order identifier"
          - name: CustomerID
            description: "Foreign key to Customers table"
          - name: EmployeeID
            description: "Foreign key to Employees table"
          - name: OrderDate
            description: "Date when the order was placed"
          - name: ShippedDate
            description: "Date when the order was shipped"

      - name: Order Details
        description: "Line items for each order with product and pricing details"
        columns:
          - name: OrderID
            description: "Foreign key to Orders table (composite primary key)"
          - name: ProductID
            description: "Foreign key to Products table (composite primary key)"
          - name: UnitPrice
            description: "Price per unit at the time of order"
          - name: Quantity
            description: "Number of units ordered"
          - name: Discount
            description: "Discount percentage applied (0.0 to 1.0)"

      - name: Products
        description: "Product catalog information"
        columns:
          - name: ProductID
            description: "Primary key - unique product identifier"
          - name: ProductName
            description: "Name of the product"
          - name: SupplierID
            description: "Foreign key to Suppliers table"
          - name: CategoryID
            description: "Foreign key to Categories table"
          - name: UnitPrice
            description: "Current price per unit"
          - name: UnitsInStock
            description: "Current inventory level"
          - name: Discontinued
            description: "Flag indicating if product is discontinued"

      - name: Categories
        description: "Product category information"
        columns:
          - name: CategoryID
            description: "Primary key - unique category identifier"
          - name: CategoryName
            description: "Name of the category"
          - name: Description
            description: "Description of the category"

      - name: Suppliers
        description: "Supplier company information"
        columns:
          - name: SupplierID
            description: "Primary key - unique supplier identifier"
          - name: CompanyName
            description: "Name of the supplier company"
          - name: ContactName
            description: "Name of the primary contact person"
          - name: Country
            description: "Country where the supplier is located"

      - name: Employees
        description: "Employee information including personal and job details"
        columns:
          - name: EmployeeID
            description: "Primary key - unique employee identifier"
          - name: LastName
            description: "Employee's last name"
          - name: FirstName
            description: "Employee's first name"
          - name: Title
            description: "Employee's job title"
          - name: HireDate
            description: "Date when the employee was hired"